### ISSUE TITLE
Display preview grouped by folder (similar to screenshot in readme)

### ISSUE THREAD

**Issue by nochso** [DiSiqueira/Gorganizer#12]
Instead of printing a simple log, it would be nice if the changes would be grouped by folder. Just like in the screenshot in the readme.

e.g.

```
Videos
    a.mkv
    b.avi

Documents
    CV.doc
...
```

IMO it's way easier to read and see what's going on.

**Comment by d6o** [comment]
Great idea! I will develop it as feature as soon i come back to my home

**Comment by d6o** [comment]
I implemented this too in #22 also implemented a tree view in All Rules
