### ISSUE TITLE
Cannot add mp4 ext to rules list 

### ISSUE THREAD

**Issue by jlapaix** [DiSiqueira/Gorganizer#14]
I'm able to add other extensions (opf for example) but not mp4.
![gorgan](https://cloud.githubusercontent.com/assets/7276380/21584941/db01678e-d083-11e6-8c7c-d64043bf5f84.png)

**Comment by nochso** [comment]
This seems to be the cause: https://github.com/DiSiqueira/Gorganizer/blob/1b101fb68d18bbd9572d898aac8e1d6295d8d9b1/rules.go#L9

I'll send a PR.

**Comment by d6o** [comment]
Thank you @jlapaix for the report!

**Comment by d6o** [comment]
Thanks @nochso i will merge your PR

**Comment by d6o** [comment]
PR reviewed and merged!
