### ISSUE TITLE
Move from bolt to other storage

### ISSUE THREAD

**Issue by nochso** [DiSiqueira/Gorganizer#2]
Hi, I've already commented on your reddit post as *porkbonk*.

Ideas for another way to store and query rules:

- JSON (see [encoding/json](https://golang.org/pkg/encoding/json/))
    ```
    {
        "Music": [
            "mp3",
            "wav"
        ],
            "Archive": [
            "7z",
            "tar"
        ]
    }
    ```
- CSV with varying amount of columns (see [encoding/csv](https://golang.org/pkg/encoding/csv/)). This is easy and easy to edit. But it will be difficult to extend or add new features.
    ```
    Music;mp3;wav
    Archive;7z;tar
    ```

Otherwise YAML or TOML might be the most user friendly, but then you'd have an external dependency.

**Comment by d6o** [comment]
Do you think is better remove Bolt completely or keep it as an alternative storage?

**Comment by nochso** [comment]
I'd remove it completely. Otherwise it might become needlessly complex and users get confused.

**Comment by wI2L** [comment]
TOML is better for human editing. I think it's ok to have a dependency for this or either YAML.

**Comment by nochso** [comment]
~~Like I said, TOML would add an external dependency.~~ However I agree, it's relatively human-friendly:

```toml
Music = ["mp3", "wav"]
Archive = ["7z", "tar"]
```

**Comment by wI2L** [comment]
Also, if a dependency is a problem, it is still possible to use a ini ike format : 
```
[music]
mp3
wav

[archive]
7z
tar
```

Parsing this is straightforward and is even easier to edit by hand for a human.

**Comment by d6o** [comment]
https://github.com/DiSiqueira/Gorganizer/pull/5

BoltDB was removed, now ini files are used to store user data

Thank you all for the contribution!!
