### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by muralikodali** [DiSiqueira/Gorganizer#27]
In ubuntu mate 16.04 , when i try install locally with **$ go get github.com/DiSiqueira/Gorganizer**, following error message is shown on terminal:

../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/gorganizer.go:31:23: cannot use newFile (type gotree.GTStructure) as type *gotree.GTStructure in append
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/gorganizer.go:39:26: cannot use newFile (type gotree.GTStructure) as type *gotree.GTStructure in append
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/gorganizer.go:40:21: cannot use newFolder (type gotree.GTStructure) as type *gotree.GTStructure in append
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/gorganizer.go:114:18: cannot use tree (type gotree.GTStructure) as type *gotree.GTStructure in argument to gotree.PrintTree
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/ini.go:71:29: cannot use treeItem (type gotree.GTStructure) as type *gotree.GTStructure in append
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/ini.go:74:22: cannot use treeFolder (type gotree.GTStructure) as type *gotree.GTStructure in append
../.gvm/pkgsets/go1.10/global/src/github.com/DiSiqueira/Gorganizer/ini.go:78:18: cannot use tree (type gotree.GTStructure) as type *gotree.GTStructure in argument to gotree.PrintTree

**Comment by d6o** [comment]
Hello @muralikodali! 

Thank you for your report! I'll take a look at it later today.

**Comment by mildlyoriginal** [comment]
@DiSiqueira, I fixed the pointer issues in #28.

**Comment by d6o** [comment]
I just merged @mildlyoriginal PR, it's fixed now, I'm going to close the issue, but if you find anything else, please feel free to post it here or open another one.
