### ISSUE TITLE
Load rules from central location

### ISSUE THREAD

**Issue by nochso** [DiSiqueira/Gorganizer#3]
Instead of a file in the current working directory, use a user-specific path.

e.g. `$HOME/.gorganizer.json`, see [os/user.User](https://golang.org/pkg/os/user/#User)

If some folders are "special" and need other settings you could do it like this:

1. Check current working directory for `.gorganizer.json` and use it it only if it exists.
2. Otherwise use `$HOME/.gorganizer.json` as a default.

That way you can have folder-specific settings if you want. Otherwise it's user-specific.

**Comment by d6o** [comment]
Thank you for this suggestion i just merged a Pull request with this feature.
https://github.com/DiSiqueira/Gorganizer/pull/6
