### ISSUE TITLE
Release 0.1 is not packaged correctly

### ISSUE THREAD

**Issue by Dr-Terrible** [DiSiqueira/Gorganizer#4]
v0.1's tarball doesn't contain any valid source code:
```shell
$ tree .
.
├── bin
│   └── gorganizer
├── gorganizer-logo.png
├── LICENSE
├── README.md
└── src
    ├── bolt.go
    ├── defaultdb.go
    ├── gorganizer.go
    └── rules.go

2 directories, 8 files
```

which prevents me from packaging `Gorganizer` for [Gentoo/Linux](https://github.com/Dr-Terrible/go-overlay/tree/master/dev-util/gorganizer), since I get :

> can't load package: package github.com/DiSiqueira/Gorganizer: no buildable Go source files in /var/tmp/portage/dev-util/gorganizer-0.1/work/gopath/src/github.com/DiSiqueira/Gorganizer

For the moment I temporarily resolved by pulling in the HEAD of the repository instead of the tarball.
Please, meanwhile can you supply a proper tarball release with all the source codes? Thank you :)

p.s.: don't package Gorganizer's executable inside the tarball, it's considered a bad practise.

**Comment by d6o** [comment]
Just created a 0.2 release, BoltDB was removed and now ini files are used to store user data, also removed gorganizer executable from tarball.

Thank you for this, any other contribution will be welcome :)

**Comment by Dr-Terrible** [comment]
Thank you @DiSiqueira.
I have updated the Gentoo/Linux package for v0.3, and everything is working as expected.

p.s.: you should enlist Gorganizer to [Awesome-Go](https://github.com/avelino/awesome-go) ;)
