### ISSUE TITLE
Move default rules into a .txt or CSV file.

### ISSUE THREAD

**Issue by chrisetheridge** [DiSiqueira/Gorganizer#7]
The default rules should be moved into a `.txt` or `.csv` file. This will allow *normal* users (i.e, non-developers) to add rules easily and still use Gorganizer :-)

**Comment by nochso** [comment]
See issue #2, already fixed by PR #5 :)

**Comment by d6o** [comment]
Exactly like @nochso  said, take a look on those links.

Sorry about the delay, i am traveling poor Internet connection and no notebook
